# Generated by Django 2.1.2 on 2020-12-25 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bucket Name')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 12, 25, 8, 53, 55, 832915), verbose_name='Date TIme')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Todo')),
                ('target', models.DateTimeField(blank=True, null=True, verbose_name='Date TIme')),
                ('created_datetime', models.DateTimeField(default=datetime.datetime(2020, 12, 25, 8, 53, 55, 833380), verbose_name='Date TIme')),
                ('completed', models.BooleanField(default=False)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_bucket', to='todo.Bucket')),
            ],
        ),
    ]
