# Generated by Django 2.1.2 on 2020-12-25 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='details',
            field=models.TextField(default=1, verbose_name='Details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bucket',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 10, 16, 58, 165369), verbose_name='Date TIme'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 10, 16, 58, 165762), verbose_name='Date TIme'),
        ),
    ]
